### PR TITLE
Develop Hello Microverse project for code review practice. 

### PR DESCRIPTION
**Pull request by Alfred-KInyua**
In this project, I have set up a "Hello world" repository.
The required tasks include.

- Creating a new branch called Develop according to GitHub flow requirements.
- Added style.css page, styling the header class section of the HTML header.
- Added the .gitignore file that contains the test.md and node_modules, which should be ignored by git.
- Setup a linter to flag programming errors, bugs, stylistic errors, and suspicious constructs in my HTML and CSS 
- Added index.html file with h1 element containing the text "Hello Microverse".
- Added the MIT file to grant permissions and indemnify developers for future use.
- Added a README.md file explaining what has been uploaded in a professional manner.

### CODE REVIEW

**Review by Wes-Isaac — CHANGES_REQUESTED** [review]
Hi @EasyPanther, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linters are on point ✔
- Splendid work with the README file 👀
- Proper use of GitHub flow 👌

## Required Changes ♻️

- [x] [**_REQUIRED_**] One of the rules of a professional repo is that the pull request has a descriptive title and meaningful summary, please edit the description part.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Alfred-KInyua** [comment]
@Wes-Isaac 
Thank you for the review, sir. I have updated my title and added a description to my PR. 
please have a look at it and advice.

**Comment by Wes-Isaac** [comment]
> 
Great job  @EasyPanther, please go to the dashboard and ask for a review, thanks.

**Review by m05e5 — APPROVED** [review]
# Hi @EasyPanther , 

### Status: Approved ✔️
goodjob


:+1: You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

[Highly Recommended]
- _( optional )_ Please as part of the requirement, its better to put your "< h1 >" tag in a "< header >" tag for your code to be more semantic and for SEO

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
